---

port: 4000
host: 0.0.0.0
safe: true


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
encoding: utf-8
markdown: kramdown
highlighter: pygments
collections:
- panels


### content configuration ###
title:       "Tanner Montague Music"
keywords:    "Jazz Drummer, Piano, Drummer for band."
description: "I know how to play drums with a band. "
source_link: "https://github.com/tannermontague/tannermontague"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-61052500-11 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  turquoise: '#1abc9c'
  emerald: '#2ecc71'
  peter-river: '#3498db'
  amethyst: '#9b59b6'
  wet-asphalt: '#34495e'
  green-sea: '#16a085'
  nephritis: '#27ae60'
  belize-hole: '#2980b9'
  wisteria: '#8e44ad'
  midnight-blue: '#2c3e50'
  sun-flower: '#f1c40f'
  carrot: '#e67e22'
  alizarin: '#e74c3c'
  clouds: '#ecf0f1'
  concrete: '#95a5a6'
  orange: '#f39c12'
  pumpkin: '#d35400'
  pomegranate: '#c0392b'
  silver: '#bdc3c7'
  asbestos: '#7f8c8d'

kramdown:
  auto_ids:  false
